/*
 * Twilio - Media
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.30.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListMediaProcessorResponse {
    #[serde(rename = "media_processors", skip_serializing_if = "Option::is_none")]
    pub media_processors: Option<Vec<crate::models::MediaV1MediaProcessor>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::ListMediaProcessorResponseMeta>>,
}

impl ListMediaProcessorResponse {
    pub fn new() -> ListMediaProcessorResponse {
        ListMediaProcessorResponse {
            media_processors: None,
            meta: None,
        }
    }
}
