/*
 * Twilio - Flex
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.30.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FlexV1Interaction {
    /// The Interaction's channel
    #[serde(rename = "channel", skip_serializing_if = "Option::is_none")]
    pub channel: Option<serde_json::Value>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<serde_json::Value>,
    /// A JSON Object representing the routing rules for the Interaction Channel
    #[serde(rename = "routing", skip_serializing_if = "Option::is_none")]
    pub routing: Option<serde_json::Value>,
    /// The unique string that identifies the resource
    #[serde(rename = "sid", skip_serializing_if = "Option::is_none")]
    pub sid: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl FlexV1Interaction {
    pub fn new() -> FlexV1Interaction {
        FlexV1Interaction {
            channel: None,
            links: None,
            routing: None,
            sid: None,
            url: None,
        }
    }
}
