/*
 * Twilio - Flex
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.30.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FlexV1InteractionInteractionChannelInteractionChannelInvite {
    /// The Channel SID for this Invite
    #[serde(rename = "channel_sid", skip_serializing_if = "Option::is_none")]
    pub channel_sid: Option<String>,
    /// The Interaction SID for this Channel
    #[serde(rename = "interaction_sid", skip_serializing_if = "Option::is_none")]
    pub interaction_sid: Option<String>,
    /// A JSON object representing the routing rules for the Interaction Channel
    #[serde(rename = "routing", skip_serializing_if = "Option::is_none")]
    pub routing: Option<serde_json::Value>,
    /// The unique string that identifies the resource
    #[serde(rename = "sid", skip_serializing_if = "Option::is_none")]
    pub sid: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl FlexV1InteractionInteractionChannelInteractionChannelInvite {
    pub fn new() -> FlexV1InteractionInteractionChannelInteractionChannelInvite {
        FlexV1InteractionInteractionChannelInteractionChannelInvite {
            channel_sid: None,
            interaction_sid: None,
            routing: None,
            sid: None,
            url: None,
        }
    }
}
