/*
 * Twilio - Flex
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.30.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListInteractionChannelResponse {
    #[serde(rename = "channels", skip_serializing_if = "Option::is_none")]
    pub channels: Option<Vec<crate::models::FlexV1InteractionInteractionChannel>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::ListChannelResponseMeta>>,
}

impl ListInteractionChannelResponse {
    pub fn new() -> ListInteractionChannelResponse {
        ListInteractionChannelResponse {
            channels: None,
            meta: None,
        }
    }
}
