/*
 * Twilio - Flex
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.30.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListInteractionChannelInviteResponse {
    #[serde(rename = "invites", skip_serializing_if = "Option::is_none")]
    pub invites:
        Option<Vec<crate::models::FlexV1InteractionInteractionChannelInteractionChannelInvite>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::ListChannelResponseMeta>>,
}

impl ListInteractionChannelInviteResponse {
    pub fn new() -> ListInteractionChannelInviteResponse {
        ListInteractionChannelInviteResponse {
            invites: None,
            meta: None,
        }
    }
}
