/*
 * Twilio - Pricing
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.30.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PricingV1MessagingMessagingCountryInstanceOutboundSmsPricesInner {
    #[serde(rename = "carrier", skip_serializing_if = "Option::is_none")]
    pub carrier: Option<String>,
    #[serde(rename = "mcc", skip_serializing_if = "Option::is_none")]
    pub mcc: Option<String>,
    #[serde(rename = "mnc", skip_serializing_if = "Option::is_none")]
    pub mnc: Option<String>,
    #[serde(rename = "prices", skip_serializing_if = "Option::is_none")]
    pub prices: Option<Vec<crate::models::PricingV1MessagingMessagingCountryInstanceOutboundSmsPricesInnerPricesInner>>,
}

impl PricingV1MessagingMessagingCountryInstanceOutboundSmsPricesInner {
    pub fn new() -> PricingV1MessagingMessagingCountryInstanceOutboundSmsPricesInner {
        PricingV1MessagingMessagingCountryInstanceOutboundSmsPricesInner {
            carrier: None,
            mcc: None,
            mnc: None,
            prices: None,
        }
    }
}
