/*
 * Twilio - Supersim
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.30.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListIpCommandResponse {
    #[serde(rename = "ip_commands", skip_serializing_if = "Option::is_none")]
    pub ip_commands: Option<Vec<crate::models::SupersimV1IpCommand>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::ListEsimProfileResponseMeta>>,
}

impl ListIpCommandResponse {
    pub fn new() -> ListIpCommandResponse {
        ListIpCommandResponse {
            ip_commands: None,
            meta: None,
        }
    }
}
