/*
 * Twilio - Supersim
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.30.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListEsimProfileResponse {
    #[serde(rename = "esim_profiles", skip_serializing_if = "Option::is_none")]
    pub esim_profiles: Option<Vec<crate::models::SupersimV1EsimProfile>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::ListEsimProfileResponseMeta>>,
}

impl ListEsimProfileResponse {
    pub fn new() -> ListEsimProfileResponse {
        ListEsimProfileResponse {
            esim_profiles: None,
            meta: None,
        }
    }
}
